### ISSUE TITLE
from SiameseModel import Recognizer

### ISSUE THREAD

**Issue by varma7** [shubham0204/Face_Recognition_with_TF#3]
Traceback (most recent call last):
  File "MainFile.py", line 3, in <module>
    from SiameseModel import Recognizer
  File "/content/Face_Recognition_with_TF/SiameseModel.py", line 4, in <module>
    import tensorflow.python.keras.backend as K
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'python'

**Comment by rushirg** [comment]
Looks like there is an issue with TensorFlow version that you are using that's why you were unable to import  ` import tensorflow.python.keras.backend as K` 
(more info: https://stackoverflow.com/a/47306203/4476612)

**Comment by varma7** [comment]
How to Know The Version @shubham0204 Used For This 
I have tried But Its Not Working and Many Conflicts
@rushirg

**Comment by rushirg** [comment]
@varma7 As per the [documentation](https://github.com/keras-team/keras) use `tf.keras`
